### ISSUE TITLE
PATH and .bashrc

### ISSUE THREAD

**Issue by friedbrice** [IsToomersCornerBeingRolledRightNow/theAppThatLetsUsProcessToomersCornerBeingRolled#1]
in the file `bootstrap`, on line 18, we export an environmental variable.

We should not have this line in bootstrap, we should manually add that line to the user's .bashrc so that the change will persist across logout and  in other bash shells that could spawned by other processes.

Sine that line will be in .bashrc, we do not need it in bootstrap, since it would be redundant.

Also, I don't think the tilde `~` resolves correctly in scripts---you should only use it in interactive prompts. In scripts, you should use `$HOME` wherever you would otherwise use a `~`.

**Comment by StevenClontz** [comment]
Fixed in 3e651524f95bfc5c56cecc30f24deefbe0173fb7
