### ISSUE TITLE
discount too-perfect vertical lines

### ISSUE THREAD

**Issue by StevenClontz** [IsToomersCornerBeingRolledRightNow/theAppThatLetsUsProcessToomersCornerBeingRolled#3]
https://twitter.com/IsToomersRolled/status/574265060991705088

Apparently we may occasionally get video errors like this. I predict that some false positives may be avoided by assuming that if we get too many perfectly horizontal gradients, then it is the result of this error. Thoughts?

**Comment by StevenClontz** [comment]
As of @friedbrice commit f6ceb6e8efd9bf836c6a7640a136f3eac38e38dc we should be getting cleaner images, so I'll close this in a week unless we hit more false positives.

**Comment by ZSarver** [comment]
I am extremely reluctant to apply more than one fix for the same issue. I agree, let's wait to see if we get any more false positives before we try to do something more complicated. In particular, we don't know that every garbled image we get will be of this form, or if even *any* other garbled image will look like this.

**Comment by ZSarver** [comment]
I am extremely reluctant to apply more than one fix for the same issue. I agree, let's wait to see if we get any more false positives before we try to do something more complicated. In particular, we don't know that every garbled image we get will be of this form, or if even _any_ other garbled image will look like this.

**Comment by StevenClontz** [comment]
:+1:

**Comment by StevenClontz** [comment]
We haven't seen any video feed errors in the last two weeks, so I'm closing this.

**Comment by friedbrice** [comment]
Steven, do you know anything about (a) our competitor's projects, or (b)
when we'll hear the results?

**Comment by ZSarver** [comment]
Competitors?
