### ISSUE TITLE
reprovisioning production app

### ISSUE THREAD

**Issue by StevenClontz** [IsToomersCornerBeingRolledRightNow/theAppThatLetsUsProcessToomersCornerBeingRolled#5]
So, apparently spinning up a 100GB disk image on AWS costs $10/mo even on the Free Tier, so I'm reprovisioning the app in the cloud to use a 8GB image (since I think we fixed the caching error we had earlier).

I'm running the binary, and getting this error

```
theApp.bin: user error (Pattern match failure in do expression at Canny.hs:62:5-23)
```

Someone who wrote that, please remind me how to fix that (bonus points for documenting appropriate usage). Thanks! :-)

**Comment by friedbrice** [comment]
It looks like the same error, `canney.hs` expects to find files that aren't there. I'll look at is ASAP.

**Comment by StevenClontz** [comment]
So maybe we should document this, but the issue was that was executing `theapp.bin` instead of `controller.sh`. Thanks @friedbrice for pointing that out. Closed.
